#!/usr/bin/env python3
"""
MILP / FCFS Post-Processing for Autonomous Intersection Experiments
===================================================================

This script post-processes the simulation results used in the thesis study
of early versus late centralized intervention at a signal-less orthogonal
intersection.

Purpose
-------
The script performs two related analyses:

1. It extracts trajectory, MILP model-size, Gurobi runtime, MIP-gap, and
   full-run timing statistics from the existing simulation experiments.

2. It constructs an idealized First-Come, First-Served (FCFS) scheduling
   baseline for comparison with the trajectory-based MILP controller.

The FCFS benchmark is NOT a dynamically simulated vehicle controller.
It is a radius-independent event-based scheduling reference that preserves
the generated agent arrival order and assigns virtual intersection service
times using fixed same-flow and cross-flow separation headways.

FCFS formulation
----------------
Agents are processed in their generated arrival order. In these simulations,
the global UID is assigned according to that generation order and is therefore
used as the FCFS ordering key.

For agent k, let:

    A_k = nominal arrival/release time,
    T_k = scheduled FCFS service time.

The required service headway is

    h_same  = d_safe / V_nominal
            = 3 / 15
            = 0.2 s

for consecutive agents from the same flow, and

    h_cross = d_sep / V_nominal
            = 4 / 15
            ≈ 0.2667 s

for consecutive agents from conflicting flows.

The event-based FCFS schedule is

    T_1 = A_1

    T_k = max(A_k, T_{k-1} + h_k)

and the corresponding virtual scheduling delay is

    D_k^FCFS = T_k - A_k.

Therefore, the FCFS result represents scheduling delay only. It does not
represent a physical stop, acceleration maneuver, or dynamically simulated
trajectory, and no velocity-adjustment metric is assigned to the FCFS
benchmark.

Radius independence
-------------------
Only one FCFS benchmark is generated for each traffic realization
(lambda_x = lambda_y = 0.9, 0.7, or 0.5 s^-1). The FCFS value is independent
of control-zone radius R and is used as a common arrival-order reference for
all MILP radii at the same traffic density.

Common evaluation population
----------------------------
The simulations use a finite arrival-generation window. Consequently, some
late-generated agents may not complete their full control-zone traversal in
every simulation.

For each traffic density, the script therefore identifies the largest
consecutive global-UID prefix that has a complete trajectory in every
AVAILABLE trajectory file used for comparison. The same common population is
then used for the MILP delay and FCFS calculations.

If a trajectory JSON is missing for a run, that run is excluded only from
trajectory-delay/common-population calculations. Its Gurobi model-size,
solver-runtime, MIP-gap, and available wall-clock statistics are still
retained. No missing trajectory delay is imputed.

MILP delay
----------
For each completed MILP trajectory, the script determines the time at which
the agent crosses the -R and +R control-zone boundaries using linear
interpolation between simulation samples.

The trajectory-based delay is

    delay_q(R)
        = [t_exit,q(R) - t_entry,q(R)]
          - 2R / V_nominal.

This is evaluated over the same common agent population used for the FCFS
comparison.

Computational analysis
----------------------
The script parses the individual Gurobi log files generated by the
receding-horizon MILP simulations and records, among other quantities:

    - original model rows and columns,
    - continuous, integer, and binary variable counts,
    - presolved model dimensions,
    - number of general constraints,
    - solver runtime,
    - branch-and-bound nodes,
    - simplex iterations,
    - final MIP gap,
    - solver termination status.

Per-solve Gurobi runtime is kept separate from the complete program
wall-clock duration. When both are available, their difference represents
aggregate non-solver overhead, including model construction, constraint
generation, Python-side simulation operations, state updates, data handling,
and file I/O.

Traffic cases
-------------
The script processes three equal per-flow arrival rates:

    lambda_x = lambda_y = 0.9 s^-1
    lambda_x = lambda_y = 0.7 s^-1
    lambda_x = lambda_y = 0.5 s^-1

For each density, the following control-zone radii are analyzed:

    R = 40, 60, 80, 100, 120, 140, 160, 180, 200 m

and both controller configurations are considered:

    fair = False
    fair = True

This gives 3 x 9 x 2 = 54 requested MILP experiment folders.

Important note on the high-density fairness case
------------------------------------------------
The fairness-enabled R = 40 m simulation for
lambda_x = lambda_y = 0.9 s^-1 did not produce a complete trajectory file.
Its trajectory-derived delay is therefore left blank. Available Gurobi
statistics recorded before termination are retained.

Analytical FCFS approximation
-----------------------------
The script additionally reports empirical and configured-rate M/G/1 waiting
time approximations. These quantities are supplementary analytical references.

The finite-sample FCFS benchmark used in the MILP comparison is the direct
event-based recursion described above, not the M/G/1 approximation.

Main outputs
------------
Results are written under:

    /ibex/user/ghoriss/FCFS_MILP_postprocess_seed20/

Important summary files include:

    paper_summary.csv
        One row for each MILP traffic/radius/fairness configuration.

    paper_comparison_wide.csv
        Fairness-disabled and fairness-enabled MILP results presented
        side-by-side together with the traffic-matched FCFS reference.

    fcfs_summary.csv
        One radius-independent FCFS result for each traffic density.

    common_population_summary.csv
        Common evaluation population and trajectory-availability checks.

    experiment_inventory.csv
        Paths, configuration information, and available source files for
        each experiment.

    parameters.csv
        Parameters used by the post-processing analysis.

Detailed per-agent FCFS results, MILP delays, and per-solve Gurobi
statistics are also written to the corresponding per-traffic directories.

Reproducibility and data handling
---------------------------------
The script is read-only with respect to the original simulation experiment
directories. It creates only post-processing outputs and cache files under
OUTPUT_ROOT.

The study uses one fixed traffic realization (seed = 20) for each traffic
density. Consequently, reported percentiles characterize variation within
that realization and should not be interpreted as confidence intervals over
independent traffic realizations.

Author
------
Salman Ghori

Research context
----------------
PhD research on early versus late traffic management for autonomous agents,
including efficiency, crossing-order fairness, and computational scaling of
receding-horizon MILP coordination.
"""

from __future__ import annotations

import csv
import gzip
import json
import math
import os
import re
import statistics
import sys
import time
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Dict, Iterable, Iterator, List, Optional, Sequence, Tuple

# =============================================================================
# USER SETTINGS
# =============================================================================

ROOT = Path("/ibex/user/ghoriss")
OUTPUT_ROOT = ROOT / "FCFS_MILP_postprocess_seed20"

RADII = [40, 60, 80, 100, 120, 140, 160, 180, 200]
I_VALUE = 4
SAFE_DISTANCE = 3
HORIZON = 60
SEED = 20

# Simulation/model constants used in the supplied code/runs.
DT = 0.1
V_NOMINAL = 15.0
D_SAFE = 3.0
D_SEP = 4.0
U_MIN = -5.0
U_MAX = 5.0
TOTAL_ITERATIONS = 36000
STOP_ADD = 0
SOURCE_X = -240.0
SOURCE_Y = +240.0

# Number of concurrent small-file log readers.  Increase cautiously on Lustre.
LOG_WORKERS = 8

# Cache expensive Gurobi log parsing.  Safe to leave True.
USE_SOLVER_CACHE = True
USE_TRAJECTORY_CACHE = True

# Missing trajectory JSON files are allowed.  The Week folder can still be
# analyzed for Gurobi/runtime metrics, while delay fields remain blank.
ALLOW_MISSING_TRAJECTORIES = True

# Keep this True if all 54 Week experiment folders themselves should exist.
# A missing trajectory JSON is NOT treated as a missing run.
REQUIRE_ALL_54_RUN_FOLDERS = True

TRAFFIC_CASES = [
    {
        "label": "lambda_0p9",
        "lambda_x": 0.9,
        "lambda_y": 0.9,
        "false_root": ROOT / "Longduration",
        "true_root": ROOT / "Longduration_fairness",
    },
    {
        "label": "lambda_0p7",
        "lambda_x": 0.7,
        "lambda_y": 0.7,
        "false_root": ROOT / "Longduration_1_low",
        "true_root": ROOT / "Longduration_fairness_1_low",
    },
    {
        "label": "lambda_0p5",
        "lambda_x": 0.5,
        "lambda_y": 0.5,
        "false_root": ROOT / "Longduration_2_low",
        "true_root": ROOT / "Longduration_fairness_2_low",
    },
]

# =============================================================================
# Generic helpers
# =============================================================================

EPS = 1.0e-9
WEEK_RE = re.compile(
    r"^Week_(?P<R>\d+)_step_(?P<step>.+?)_S_(?P<S>\d+)_I_(?P<I>\d+)_H_(?P<H>\d+)_C_(?P<C>True|False)$"
)
LOG_ITER_RE = re.compile(r"gurobi_(\d+)_R_", re.I)


def percentile(values: Sequence[float], q: float) -> Optional[float]:
    if not values:
        return None
    x = sorted(float(v) for v in values)
    if len(x) == 1:
        return x[0]
    p = q * (len(x) - 1)
    lo = int(math.floor(p))
    hi = int(math.ceil(p))
    if lo == hi:
        return x[lo]
    w = p - lo
    return x[lo] * (1.0 - w) + x[hi] * w


def stats(values: Sequence[float]) -> dict:
    x = [float(v) for v in values if v is not None and math.isfinite(float(v))]
    if not x:
        return {
            "count": 0,
            "mean": None,
            "median": None,
            "std": None,
            "p95": None,
            "max": None,
            "min": None,
            "total": 0.0,
        }
    return {
        "count": len(x),
        "mean": statistics.fmean(x),
        "median": statistics.median(x),
        "std": statistics.pstdev(x) if len(x) > 1 else 0.0,
        "p95": percentile(x, 0.95),
        "max": max(x),
        "min": min(x),
        "total": math.fsum(x),
    }


def write_csv(path: Path, rows: Sequence[dict], fieldnames: Optional[Sequence[str]] = None) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    rows = list(rows)
    if fieldnames is None:
        fields: List[str] = []
        seen = set()
        for row in rows:
            for key in row:
                if key not in seen:
                    seen.add(key)
                    fields.append(key)
        fieldnames = fields
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(fieldnames), extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)


def write_csv_gz(path: Path, rows: Iterable[dict], fieldnames: Sequence[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with gzip.open(path, "wt", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(fieldnames), extrasaction="ignore")
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def latest_file(folder: Path, pattern: str) -> Optional[Path]:
    items = [p for p in folder.glob(pattern) if p.is_file()]
    return max(items, key=lambda p: p.stat().st_mtime) if items else None


def scalar(value) -> float:
    while isinstance(value, (list, tuple)):
        if not value:
            raise ValueError("Empty nested coordinate list")
        value = value[0]
    return float(value)


def json_load_maybe(path: Optional[Path]) -> dict:
    if path is None or not path.exists():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        return data if isinstance(data, dict) else {}
    except Exception as exc:
        return {"parse_error": str(exc)}


def iter_top_level_json_array(path: Path, chunk_size: int = 16 * 1024 * 1024) -> Iterator[object]:
    """Stream items from a top-level JSON array using only Python stdlib."""
    decoder = json.JSONDecoder()
    with path.open("r", encoding="utf-8") as f:
        buf = ""
        pos = 0
        started = False
        eof = False
        while True:
            if not eof and (pos >= len(buf) or len(buf) - pos < chunk_size // 4):
                rem = buf[pos:]
                chunk = f.read(chunk_size)
                eof = chunk == ""
                buf = rem + chunk
                pos = 0

            while pos < len(buf) and buf[pos].isspace():
                pos += 1

            if not started:
                if pos >= len(buf):
                    if eof:
                        raise ValueError(f"Empty JSON file: {path}")
                    continue
                if buf[pos] != "[":
                    raise ValueError(f"Expected top-level JSON array: {path}")
                pos += 1
                started = True

            while pos < len(buf) and (buf[pos].isspace() or buf[pos] == ","):
                pos += 1
            if pos < len(buf) and buf[pos] == "]":
                return
            if pos >= len(buf):
                if eof:
                    raise ValueError(f"Unexpected EOF in {path}")
                continue

            try:
                item, end = decoder.raw_decode(buf, pos)
            except json.JSONDecodeError:
                if eof:
                    raise
                rem = buf[pos:]
                chunk = f.read(chunk_size)
                eof = chunk == ""
                buf = rem + chunk
                pos = 0
                continue

            yield item
            pos = end


# =============================================================================
# Run discovery
# =============================================================================

@dataclass(frozen=True)
class RunKey:
    traffic_label: str
    radius: int
    fair: bool


@dataclass
class RunFiles:
    key: RunKey
    traffic_lambda_x: float
    traffic_lambda_y: float
    root: Path
    radius_dir: Path
    week_dir: Path
    trajectory_file: Optional[Path]
    runtime_file: Optional[Path]
    mip_json_file: Optional[Path]
    source_code_file: Optional[Path]
    step_token: str
    safe_distance: int
    i_value: int
    horizon: int


def discover_one_run(case: dict, radius: int, fair: bool) -> RunFiles:
    root = Path(case["true_root"] if fair else case["false_root"])
    radius_dir = root / f"R_{radius}"
    if not radius_dir.is_dir():
        raise FileNotFoundError(f"Missing radius folder: {radius_dir}")

    matches: List[Tuple[Path, re.Match]] = []
    for p in radius_dir.glob("Week_*"):
        if not p.is_dir():
            continue
        m = WEEK_RE.match(p.name)
        if not m:
            continue
        if int(m.group("R")) != radius:
            continue
        if int(m.group("I")) != I_VALUE:
            continue
        if int(m.group("S")) != SAFE_DISTANCE:
            continue
        if int(m.group("H")) != HORIZON:
            continue
        if (m.group("C") == "True") != fair:
            continue
        matches.append((p, m))

    if not matches:
        raise FileNotFoundError(
            f"No matching Week folder in {radius_dir} for I_{I_VALUE}, "
            f"S_{SAFE_DISTANCE}, H_{HORIZON}, fair={fair}"
        )

    # If reruns exist, prefer the folder whose latest trajectory is newest.
    def score(pm: Tuple[Path, re.Match]) -> float:
        traj = latest_file(pm[0], "vehicles_positions_id_*.json")
        return traj.stat().st_mtime if traj else 0.0

    matches.sort(key=score, reverse=True)
    week_dir, m = matches[0]
    if len(matches) > 1:
        print(f"WARNING: multiple matching Week folders in {radius_dir}; using {week_dir.name}")

    trajectory = latest_file(week_dir, "vehicles_positions_id_*.json")
    if trajectory is None:
        msg = f"No vehicles_positions_id_*.json in {week_dir}"
        if ALLOW_MISSING_TRAJECTORIES:
            print(f"WARNING: {msg}; solver/runtime metrics will still be processed, delay will be blank.")
        else:
            raise FileNotFoundError(msg)

    source_candidates = sorted(radius_dir.glob("RH_1_intesection_possion_discrete_distribution_new*.py"))
    source_code = source_candidates[0] if source_candidates else None

    return RunFiles(
        key=RunKey(case["label"], radius, fair),
        traffic_lambda_x=float(case["lambda_x"]),
        traffic_lambda_y=float(case["lambda_y"]),
        root=root,
        radius_dir=radius_dir,
        week_dir=week_dir,
        trajectory_file=trajectory,
        runtime_file=latest_file(week_dir, "runtime_duration_*"),
        mip_json_file=latest_file(week_dir, "MIP_file-*.json"),
        source_code_file=source_code,
        step_token=m.group("step"),
        safe_distance=int(m.group("S")),
        i_value=int(m.group("I")),
        horizon=int(m.group("H")),
    )


def discover_all_runs() -> Dict[RunKey, RunFiles]:
    runs: Dict[RunKey, RunFiles] = {}
    errors = []
    for case in TRAFFIC_CASES:
        for radius in RADII:
            for fair in (False, True):
                try:
                    rf = discover_one_run(case, radius, fair)
                    runs[rf.key] = rf
                except Exception as exc:
                    errors.append(str(exc))
    expected = len(TRAFFIC_CASES) * len(RADII) * 2
    print(f"Discovered {len(runs)}/{expected} requested MILP runs.")
    if errors:
        for e in errors:
            print("MISSING:", e)
        if REQUIRE_ALL_54_RUN_FOLDERS:
            raise RuntimeError(f"Missing {len(errors)} requested runs; see messages above.")
    return runs


# =============================================================================
# Optional source-code configuration verification
# =============================================================================

SOURCE_PATTERNS = {
    "code_N": re.compile(r"self\.N\s*=\s*([0-9.]+)"),
    "code_dt": re.compile(r"self\.delta_t\s*=\s*([0-9.]+)"),
    "code_total_iterations": re.compile(r"self\.total_iterations\s*=\s*(\d+)"),
    "code_stop_add": re.compile(r"self\.stop_add\s*=\s*(\d+)"),
    "code_safe_dis": re.compile(r"self\.safe_dis\s*=\s*([0-9.]+)"),
    "code_buff_ins": re.compile(r"self\.buff_ins\s*=\s*([0-9.]+)"),
    "code_proximity": re.compile(r"self\.proximity\s*=\s*([0-9.]+)"),
    "code_Big_M": re.compile(r"self\.Big_M\s*=\s*([0-9.eE+-]+)"),
    "code_Big_W": re.compile(r"self\.Big_W\s*=\s*([0-9.eE+-]+)"),
    "code_vehicle_velocity": re.compile(r"self\.vehicle_velocity\s*=\s*([0-9.]+)"),
    "code_lambda_x": re.compile(r"self\.lambda_x\s*=\s*([0-9.]+)"),
    "code_lambda_y": re.compile(r"self\.lambda_y\s*=\s*([0-9.]+)"),
    "code_min_steps": re.compile(r"self\.min_steps\s*=\s*(\d+)"),
    "code_fair": re.compile(r"self\.fair\s*=\s*(True|False)"),
}


def parse_source_config(path: Optional[Path]) -> dict:
    if path is None or not path.exists():
        return {}
    text = path.read_text(encoding="utf-8", errors="ignore")
    out = {"source_code_file": str(path)}
    for key, rx in SOURCE_PATTERNS.items():
        m = rx.search(text)
        if not m:
            continue
        val = m.group(1)
        if val in {"True", "False"}:
            out[key] = val == "True"
        else:
            try:
                out[key] = int(val) if re.fullmatch(r"\d+", val) else float(val)
            except Exception:
                out[key] = val
    return out


# =============================================================================
# Trajectory parsing, exact crossing times, and delay
# =============================================================================

@dataclass
class UIDState:
    axis: str
    first_seen_time_s: Optional[float] = None
    previous: Optional[Tuple[float, float]] = None
    entry_time_s: Optional[float] = None
    center_time_s: Optional[float] = None
    exit_time_s: Optional[float] = None


def crossing_time(prev: Tuple[float, float], cur: Tuple[float, float], boundary: float) -> Optional[float]:
    t0, z0 = prev
    t1, z1 = cur
    if z1 < z0 - 1.0e-5:
        return None
    if abs(z0 - boundary) <= 1.0e-9:
        return t0
    if z0 <= boundary <= z1 and abs(z1 - z0) > EPS:
        a = (boundary - z0) / (z1 - z0)
        a = max(0.0, min(1.0, a))
        return t0 + a * (t1 - t0)
    return None


def trajectory_cache_path(rf: RunFiles) -> Path:
    base = OUTPUT_ROOT / "cache" / rf.key.traffic_label / ("fair" if rf.key.fair else "nofair")
    return base / f"R_{rf.key.radius}_trajectory_cache.json.gz"


def load_trajectory_cache(rf: RunFiles) -> Optional[Tuple[Dict[int, dict], dict]]:
    if rf.trajectory_file is None:
        return None
    if not USE_TRAJECTORY_CACHE:
        return None
    cp = trajectory_cache_path(rf)
    if not cp.exists():
        return None
    try:
        with gzip.open(cp, "rt", encoding="utf-8") as f:
            data = json.load(f)
        st = rf.trajectory_file.stat()
        meta = data.get("meta", {})
        if meta.get("source_size") != st.st_size or abs(meta.get("source_mtime", 0.0) - st.st_mtime) > 1e-6:
            return None
        rows = {int(k): v for k, v in data["rows"].items()}
        return rows, data["summary"]
    except Exception:
        return None


def save_trajectory_cache(rf: RunFiles, rows: Dict[int, dict], summary: dict) -> None:
    if rf.trajectory_file is None:
        return
    if not USE_TRAJECTORY_CACHE:
        return
    cp = trajectory_cache_path(rf)
    cp.parent.mkdir(parents=True, exist_ok=True)
    st = rf.trajectory_file.stat()
    payload = {
        "meta": {"source_size": st.st_size, "source_mtime": st.st_mtime, "source": str(rf.trajectory_file)},
        "summary": summary,
        "rows": {str(k): v for k, v in rows.items()},
    }
    with gzip.open(cp, "wt", encoding="utf-8") as f:
        json.dump(payload, f, separators=(",", ":"), allow_nan=False)


def parse_trajectory(rf: RunFiles) -> Tuple[Dict[int, dict], dict]:
    if rf.trajectory_file is None:
        raise FileNotFoundError(f"Trajectory JSON unavailable for {rf.week_dir}")
    cached = load_trajectory_cache(rf)
    if cached is not None:
        rows, summary = cached
        summary = dict(summary)
        summary["trajectory_cache_used"] = True
        return rows, summary

    radius = float(rf.key.radius)
    states: Dict[int, UIDState] = {}
    frame_count = 0
    record_count = 0
    nonmonotone = 0
    t0 = time.perf_counter()

    for frame_idx, frame in enumerate(iter_top_level_json_array(rf.trajectory_file)):
        frame_count += 1
        t = frame_idx * DT
        if not isinstance(frame, list):
            continue
        for rec in frame:
            if not isinstance(rec, (list, tuple)) or len(rec) < 6:
                continue
            record_count += 1
            x = scalar(rec[0])
            y = scalar(rec[1])
            axis = str(rec[4]).lower()
            uid = int(rec[5])
            if axis not in {"x", "y"}:
                continue
            z = x if axis == "x" else -y

            st = states.get(uid)
            if st is None:
                st = UIDState(axis=axis, first_seen_time_s=t)
                states[uid] = st
            elif st.axis != axis:
                raise ValueError(f"UID {uid} changes axis in {rf.trajectory_file}")

            if st.previous is not None:
                if z < st.previous[1] - 1.0e-5:
                    nonmonotone += 1
                if st.entry_time_s is None:
                    ct = crossing_time(st.previous, (t, z), -radius)
                    if ct is not None:
                        st.entry_time_s = ct
                if st.center_time_s is None:
                    ct = crossing_time(st.previous, (t, z), 0.0)
                    if ct is not None:
                        st.center_time_s = ct
                if st.exit_time_s is None:
                    ct = crossing_time(st.previous, (t, z), +radius)
                    if ct is not None:
                        st.exit_time_s = ct
            else:
                if abs(z + radius) <= 1.0e-7:
                    st.entry_time_s = t
                if abs(z) <= 1.0e-7:
                    st.center_time_s = t
                if abs(z - radius) <= 1.0e-7:
                    st.exit_time_s = t
            st.previous = (t, z)

        if frame_idx and frame_idx % 5000 == 0:
            print(f"    trajectory R={rf.key.radius} fair={rf.key.fair}: frame {frame_idx}")

    ideal = 2.0 * radius / V_NOMINAL
    rows: Dict[int, dict] = {}
    for uid, st in states.items():
        complete = st.entry_time_s is not None and st.exit_time_s is not None
        delay = None
        if complete:
            delay = float(st.exit_time_s - st.entry_time_s - ideal)
            if -1.0e-5 < delay < 0.0:
                delay = 0.0
        rows[uid] = {
            "uid": uid,
            "axis": st.axis,
            "first_seen_time_s": st.first_seen_time_s,
            "entry_time_s": st.entry_time_s,
            "center_time_s": st.center_time_s,
            "exit_time_s": st.exit_time_s,
            "delay_s": delay,
            "complete": complete,
        }

    summary = {
        "trajectory_file": str(rf.trajectory_file),
        "frame_count": frame_count,
        "record_count": record_count,
        "uids_seen": len(rows),
        "uids_completed": sum(1 for r in rows.values() if r["complete"]),
        "nonmonotone_sample_count": nonmonotone,
        "trajectory_parse_wall_s": time.perf_counter() - t0,
        "trajectory_cache_used": False,
    }
    save_trajectory_cache(rf, rows, summary)
    return rows, summary


def longest_complete_uid_prefix(rows: Dict[int, dict]) -> int:
    n = 0
    while True:
        uid = n + 1
        r = rows.get(uid)
        if r is None or not r.get("complete", False):
            return n
        n = uid


# =============================================================================
# Gurobi log parsing
# =============================================================================

RE_OPT = re.compile(r"Optimize a model with\s+([\d,]+)\s+rows,\s+([\d,]+)\s+columns\s+and\s+([\d,]+)\s+nonzeros", re.I)
RE_VAR = re.compile(r"Variable types:\s*([\d,]+)\s+continuous,\s*([\d,]+)\s+integer\s*\(([\d,]+)\s+binary\)", re.I)
RE_GEN = re.compile(r"Model has\s+([\d,]+)\s+general constraints", re.I)
RE_PRESOLVED = re.compile(r"Presolved:\s*([\d,]+)\s+rows,\s*([\d,]+)\s+columns,\s*([\d,]+)\s+nonzeros", re.I)
RE_ROOT = re.compile(r"Root relaxation:.*?,\s*([\d,]+)\s+iterations,\s*([0-9.eE+-]+)\s+seconds", re.I)
RE_EXPLORED = re.compile(r"Explored\s+([\d,]+)\s+nodes\s+\(([\d,]+)\s+simplex iterations\)\s+in\s+([0-9.eE+-]+)\s+seconds(?:\s+\(([0-9.eE+-]+)\s+work units\))?", re.I)
RE_BEST = re.compile(r"Best objective\s+([^,]+),\s+best bound\s+([^,]+),\s+gap\s+([^%]+)%", re.I)
RE_MULTI_START = re.compile(r"Multi-objectives:\s*starting optimization with\s+(\d+)\s+objectives", re.I)
RE_MULTI_SOLVED = re.compile(r"Multi-objectives:\s*solved in\s+([0-9.eE+-]+)\s+seconds(?:\s+\(([0-9.eE+-]+)\s+work units\))?", re.I)
RE_THREADS_USED = re.compile(r"Thread count was\s+(\d+)", re.I)


def to_int(s: str) -> int:
    return int(s.replace(",", ""))


def parse_gurobi_log(path: Path) -> dict:
    out = {
        "log_file": str(path),
        "iteration": None,
        "model_rows": None,
        "model_columns": None,
        "model_nonzeros": None,
        "original_continuous_vars": None,
        "original_integer_vars": None,
        "original_binary_vars": None,
        "general_constraints": None,
        "presolved_rows": None,
        "presolved_columns": None,
        "presolved_nonzeros": None,
        "presolved_continuous_vars": None,
        "presolved_integer_vars": None,
        "presolved_binary_vars": None,
        "objective_count": None,
        "root_relaxation_iterations": None,
        "root_relaxation_s": None,
        "nodes": None,
        "simplex_iterations": None,
        "solver_runtime_s": None,
        "solver_work_units": None,
        "best_objective": None,
        "best_bound": None,
        "final_gap_percent": None,
        "threads_used": None,
        "status": "UNKNOWN",
        "parse_error": None,
    }
    mm = LOG_ITER_RE.search(path.name)
    if mm:
        out["iteration"] = int(mm.group(1))

    first_model_seen = False
    initial_var_captured = False
    after_presolved = False

    try:
        with path.open("r", encoding="utf-8", errors="ignore") as f:
            for line in f:
                m = RE_OPT.search(line)
                if m and not first_model_seen:
                    out["model_rows"] = to_int(m.group(1))
                    out["model_columns"] = to_int(m.group(2))
                    out["model_nonzeros"] = to_int(m.group(3))
                    first_model_seen = True
                    continue

                m = RE_VAR.search(line)
                if m:
                    if first_model_seen and not initial_var_captured:
                        out["original_continuous_vars"] = to_int(m.group(1))
                        out["original_integer_vars"] = to_int(m.group(2))
                        out["original_binary_vars"] = to_int(m.group(3))
                        initial_var_captured = True
                    elif after_presolved:
                        out["presolved_continuous_vars"] = to_int(m.group(1))
                        out["presolved_integer_vars"] = to_int(m.group(2))
                        out["presolved_binary_vars"] = to_int(m.group(3))
                        after_presolved = False
                    continue

                m = RE_GEN.search(line)
                if m and out["general_constraints"] is None:
                    out["general_constraints"] = to_int(m.group(1))
                    continue

                m = RE_PRESOLVED.search(line)
                if m:
                    out["presolved_rows"] = to_int(m.group(1))
                    out["presolved_columns"] = to_int(m.group(2))
                    out["presolved_nonzeros"] = to_int(m.group(3))
                    after_presolved = True
                    continue

                m = RE_MULTI_START.search(line)
                if m:
                    out["objective_count"] = int(m.group(1))
                    continue

                m = RE_ROOT.search(line)
                if m:
                    out["root_relaxation_iterations"] = to_int(m.group(1))
                    out["root_relaxation_s"] = float(m.group(2))
                    continue

                m = RE_EXPLORED.search(line)
                if m:
                    out["nodes"] = to_int(m.group(1))
                    out["simplex_iterations"] = to_int(m.group(2))
                    # Keep this as fallback; Multi-objective solved time below is preferred.
                    out["solver_runtime_s"] = float(m.group(3))
                    if m.group(4) is not None:
                        out["solver_work_units"] = float(m.group(4))
                    continue

                m = RE_MULTI_SOLVED.search(line)
                if m:
                    out["solver_runtime_s"] = float(m.group(1))
                    if m.group(2) is not None:
                        out["solver_work_units"] = float(m.group(2))
                    continue

                m = RE_BEST.search(line)
                if m:
                    try:
                        out["best_objective"] = float(m.group(1))
                    except Exception:
                        out["best_objective"] = m.group(1).strip()
                    try:
                        out["best_bound"] = float(m.group(2))
                    except Exception:
                        out["best_bound"] = m.group(2).strip()
                    try:
                        out["final_gap_percent"] = float(m.group(3))
                    except Exception:
                        pass
                    continue

                m = RE_THREADS_USED.search(line)
                if m:
                    out["threads_used"] = int(m.group(1))

                if "Optimal solution found" in line:
                    out["status"] = "OPTIMAL"
                elif "Time limit reached" in line:
                    out["status"] = "TIME_LIMIT"
                elif "Model is infeasible" in line or "Infeasible model" in line:
                    out["status"] = "INFEASIBLE"
                elif "Sub-optimal termination" in line:
                    out["status"] = "SUBOPTIMAL"
    except Exception as exc:
        out["parse_error"] = str(exc)
    return out


SOLVER_DETAIL_FIELDS = [
    "iteration", "model_rows", "model_columns", "model_nonzeros",
    "original_continuous_vars", "original_integer_vars", "original_binary_vars",
    "general_constraints",
    "presolved_rows", "presolved_columns", "presolved_nonzeros",
    "presolved_continuous_vars", "presolved_integer_vars", "presolved_binary_vars",
    "objective_count", "root_relaxation_iterations", "root_relaxation_s",
    "nodes", "simplex_iterations", "solver_runtime_s", "solver_work_units",
    "best_objective", "best_bound", "final_gap_percent", "threads_used",
    "status", "parse_error", "log_file",
]

AGG_KEYS = [
    "model_rows", "model_columns", "model_nonzeros",
    "original_continuous_vars", "original_integer_vars", "original_binary_vars",
    "general_constraints",
    "presolved_rows", "presolved_columns", "presolved_nonzeros",
    "presolved_continuous_vars", "presolved_integer_vars", "presolved_binary_vars",
    "root_relaxation_s", "nodes", "simplex_iterations", "solver_runtime_s",
    "solver_work_units", "final_gap_percent",
]


def collect_gurobi_logs(folder: Path) -> List[Path]:
    # Deduplicate by optimization iteration, retaining newest file if rerun.
    by_it: Dict[int, Tuple[float, Path]] = {}
    with os.scandir(folder) as it:
        for ent in it:
            if not ent.is_file() or not ent.name.startswith("gurobi_") or not ent.name.endswith(".log"):
                continue
            m = LOG_ITER_RE.search(ent.name)
            if not m:
                continue
            k = int(m.group(1))
            mt = ent.stat().st_mtime
            old = by_it.get(k)
            p = Path(ent.path)
            if old is None or mt > old[0]:
                by_it[k] = (mt, p)
    return [by_it[k][1] for k in sorted(by_it)]


def solver_cache_paths(rf: RunFiles) -> Tuple[Path, Path]:
    d = OUTPUT_ROOT / "solver_detail" / rf.key.traffic_label / ("fair" if rf.key.fair else "nofair")
    return d / f"R_{rf.key.radius}_solver_iterations.csv.gz", d / f"R_{rf.key.radius}_solver_summary.json"


def logs_signature(logs: Sequence[Path]) -> dict:
    if not logs:
        return {"count": 0, "max_mtime": None, "sum_size": 0}
    count = len(logs)
    max_mtime = 0.0
    sum_size = 0
    for p in logs:
        st = p.stat()
        max_mtime = max(max_mtime, st.st_mtime)
        sum_size += st.st_size
    return {"count": count, "max_mtime": max_mtime, "sum_size": sum_size}


def summarize_solver_values(values: Dict[str, List[float]], status_counts: Dict[str, int], log_count: int, parse_error_count: int) -> dict:
    out = {
        "solver_log_count": log_count,
        "solver_parse_error_count": parse_error_count,
    }
    for key in AGG_KEYS:
        s = stats(values.get(key, []))
        for stat_name in ("mean", "median", "p95", "max", "min", "total"):
            out[f"{key}_{stat_name}"] = s[stat_name]
    for status in ("OPTIMAL", "TIME_LIMIT", "INFEASIBLE", "SUBOPTIMAL", "UNKNOWN"):
        out[f"status_{status}_count"] = int(status_counts.get(status, 0))
    return out


def parse_solver_run(rf: RunFiles) -> dict:
    logs = collect_gurobi_logs(rf.week_dir)
    sig = logs_signature(logs)
    detail_path, summary_path = solver_cache_paths(rf)
    detail_path.parent.mkdir(parents=True, exist_ok=True)

    if USE_SOLVER_CACHE and summary_path.exists() and detail_path.exists():
        try:
            cached = json.loads(summary_path.read_text(encoding="utf-8"))
            if cached.get("log_signature") == sig:
                result = cached["summary"]
                result["solver_cache_used"] = True
                result["solver_detail_file"] = str(detail_path)
                return result
        except Exception:
            pass

    print(f"    parsing {len(logs)} Gurobi logs with {LOG_WORKERS} workers")
    values: Dict[str, List[float]] = {k: [] for k in AGG_KEYS}
    status_counts: Dict[str, int] = {}
    parse_errors = 0
    t0 = time.perf_counter()

    with gzip.open(detail_path, "wt", newline="", encoding="utf-8") as gf:
        writer = csv.DictWriter(gf, fieldnames=SOLVER_DETAIL_FIELDS, extrasaction="ignore")
        writer.writeheader()
        if LOG_WORKERS > 1 and len(logs) > 1:
            with ThreadPoolExecutor(max_workers=LOG_WORKERS) as ex:
                iterator = ex.map(parse_gurobi_log, logs)
                for idx, row in enumerate(iterator, start=1):
                    writer.writerow(row)
                    for key in AGG_KEYS:
                        v = row.get(key)
                        if isinstance(v, (int, float)) and math.isfinite(float(v)):
                            values[key].append(float(v))
                    st = str(row.get("status", "UNKNOWN"))
                    status_counts[st] = status_counts.get(st, 0) + 1
                    if row.get("parse_error"):
                        parse_errors += 1
                    if idx % 5000 == 0:
                        print(f"      parsed {idx}/{len(logs)} logs")
        else:
            for idx, p in enumerate(logs, start=1):
                row = parse_gurobi_log(p)
                writer.writerow(row)
                for key in AGG_KEYS:
                    v = row.get(key)
                    if isinstance(v, (int, float)) and math.isfinite(float(v)):
                        values[key].append(float(v))
                st = str(row.get("status", "UNKNOWN"))
                status_counts[st] = status_counts.get(st, 0) + 1
                if row.get("parse_error"):
                    parse_errors += 1
                if idx % 5000 == 0:
                    print(f"      parsed {idx}/{len(logs)} logs")

    summary = summarize_solver_values(values, status_counts, len(logs), parse_errors)
    summary.update({
        "solver_log_parse_wall_s": time.perf_counter() - t0,
        "solver_cache_used": False,
        "solver_detail_file": str(detail_path),
    })
    if USE_SOLVER_CACHE:
        summary_path.write_text(
            json.dumps({"log_signature": sig, "summary": summary}, indent=2, allow_nan=False),
            encoding="utf-8",
        )
    return summary


# =============================================================================
# Radius-independent FCFS virtual waiting + analytical approximation
# =============================================================================


def run_event_fcfs(arrivals: Sequence[dict], lambda_x: float, lambda_y: float) -> Tuple[List[dict], dict]:
    t0 = time.perf_counter()
    ordered = sorted(arrivals, key=lambda r: int(r["uid"]))
    same_gap = D_SAFE / V_NOMINAL
    cross_gap = D_SEP / V_NOMINAL

    rows: List[dict] = []
    prev_service: Optional[float] = None
    prev_axis: Optional[str] = None
    transition_gaps: List[float] = []
    same_count = 0
    cross_count = 0

    for rank, arr in enumerate(ordered, start=1):
        release = float(arr["release_time_s"])
        axis = str(arr["axis"])
        if prev_service is None:
            service = release
            applied_gap = None
        else:
            applied_gap = same_gap if axis == prev_axis else cross_gap
            service = max(release, prev_service + applied_gap)
            transition_gaps.append(applied_gap)
            if axis == prev_axis:
                same_count += 1
            else:
                cross_count += 1
        wait = max(0.0, service - release)
        rows.append({
            "uid": int(arr["uid"]),
            "axis": axis,
            "arrival_rank": rank,
            "release_time_s": release,
            "scheduled_center_time_s": service,
            "applied_service_gap_s": applied_gap,
            "virtual_wait_delay_s": wait,
        })
        prev_service = service
        prev_axis = axis

    waits = [r["virtual_wait_delay_s"] for r in rows]
    ws = stats(waits)

    releases = [r["release_time_s"] for r in rows]
    lam_emp = None
    if len(releases) >= 2 and max(releases) > min(releases):
        lam_emp = (len(releases) - 1) / (max(releases) - min(releases))

    # Empirical transition-based M/G/1 approximation.
    empirical_es = statistics.fmean(transition_gaps) if transition_gaps else None
    empirical_es2 = statistics.fmean([g * g for g in transition_gaps]) if transition_gaps else None
    empirical_rho = None
    empirical_mg1 = None
    if lam_emp is not None and empirical_es is not None and empirical_es2 is not None:
        empirical_rho = lam_emp * empirical_es
        empirical_mg1 = (
            lam_emp * empirical_es2 / (2.0 * (1.0 - empirical_rho))
            if empirical_rho < 1.0 else math.inf
        )

    # Configured-rate theoretical approximation for two independent streams.
    lam_cfg = lambda_x + lambda_y
    px = lambda_x / lam_cfg if lam_cfg > 0 else 0.0
    py = lambda_y / lam_cfg if lam_cfg > 0 else 0.0
    p_same = px * px + py * py
    p_cross = 1.0 - p_same
    cfg_es = p_same * same_gap + p_cross * cross_gap
    cfg_es2 = p_same * same_gap**2 + p_cross * cross_gap**2
    cfg_rho = lam_cfg * cfg_es
    cfg_mg1 = lam_cfg * cfg_es2 / (2.0 * (1.0 - cfg_rho)) if cfg_rho < 1.0 else math.inf

    summary = {
        "method": "FCFS_EVENT_VIRTUAL_WAIT_RADIUS_INDEPENDENT",
        "agent_count": len(rows),
        "ordering": "ascending global UID",
        "same_flow_service_gap_s": same_gap,
        "cross_flow_service_gap_s": cross_gap,
        "mean_delay_s": ws["mean"],
        "median_delay_s": ws["median"],
        "std_delay_s": ws["std"],
        "p95_delay_s": ws["p95"],
        "max_delay_s": ws["max"],
        "total_delay_s": ws["total"],
        "same_transition_count": same_count,
        "cross_transition_count": cross_count,
        "empirical_lambda_total_veh_s": lam_emp,
        "empirical_mean_service_gap_s": empirical_es,
        "empirical_rho": empirical_rho,
        "empirical_mg1_mean_wait_s": empirical_mg1,
        "configured_lambda_x_veh_s": lambda_x,
        "configured_lambda_y_veh_s": lambda_y,
        "configured_lambda_total_veh_s": lam_cfg,
        "theoretical_p_same": p_same,
        "theoretical_p_cross": p_cross,
        "theoretical_mean_service_gap_s": cfg_es,
        "theoretical_rho": cfg_rho,
        "theoretical_mg1_mean_wait_s": cfg_mg1,
        "fcfs_compute_wall_s": time.perf_counter() - t0,
        "fcfs_complexity": "O(N) time, O(N) output storage, no mathematical-program solver",
        "note": (
            "The M/G/1 values are analytical approximations. The exact finite-sample FCFS "
            "value is computed directly from the common UID arrival sequence above."
        ),
    }
    return rows, summary


# =============================================================================
# Main traffic-case analysis
# =============================================================================


def analyze_traffic_case(case: dict, all_runs: Dict[RunKey, RunFiles]) -> Tuple[List[dict], dict, dict, List[dict]]:
    label = case["label"]
    case_out = OUTPUT_ROOT / label
    case_out.mkdir(parents=True, exist_ok=True)
    print("\n" + "=" * 80)
    print(f"TRAFFIC {label}: lambda_x=lambda_y={case['lambda_x']}")
    print("=" * 80)

    trajectory_data: Dict[Tuple[int, bool], Dict[int, dict]] = {}
    trajectory_summaries: Dict[Tuple[int, bool], dict] = {}
    run_rows: List[dict] = []
    inventory_rows: List[dict] = []
    missing_trajectory_runs: List[str] = []

    # Parse every trajectory that actually exists.  A missing trajectory does
    # not discard the experiment: Gurobi logs/runtime are still analyzed later.
    for radius in RADII:
        for fair in (False, True):
            key = RunKey(label, radius, fair)
            rf = all_runs[key]
            print(f"\n  R={radius}, fair={fair}")

            runtime_data = json_load_maybe(rf.runtime_file)
            source_cfg = parse_source_config(rf.source_code_file)
            trajectory_available = rf.trajectory_file is not None and rf.trajectory_file.exists()

            if trajectory_available:
                uid_rows, traj_summary = parse_trajectory(rf)
                trajectory_data[(radius, fair)] = uid_rows
                trajectory_summaries[(radius, fair)] = traj_summary
                prefix_n = longest_complete_uid_prefix(uid_rows)
            else:
                uid_rows = {}
                traj_summary = {
                    "trajectory_file": None,
                    "frame_count": None,
                    "record_count": None,
                    "uids_seen": None,
                    "uids_completed": None,
                    "nonmonotone_sample_count": None,
                    "trajectory_parse_wall_s": None,
                    "trajectory_cache_used": False,
                }
                prefix_n = None
                missing_trajectory_runs.append(f"R={radius},fair={fair}")
                print("    trajectory JSON MISSING -> delay unavailable; keeping solver/runtime analysis")

            inv = {
                "traffic_label": label,
                "lambda_x_expected": case["lambda_x"],
                "lambda_y_expected": case["lambda_y"],
                "radius_m": radius,
                "fair": fair,
                "root": str(rf.root),
                "week_dir": str(rf.week_dir),
                "trajectory_available": trajectory_available,
                "delay_available": trajectory_available,
                "trajectory_file": str(rf.trajectory_file) if rf.trajectory_file else None,
                "runtime_file": str(rf.runtime_file) if rf.runtime_file else None,
                "mip_json_file": str(rf.mip_json_file) if rf.mip_json_file else None,
                "source_code_file": str(rf.source_code_file) if rf.source_code_file else None,
                "step_token": rf.step_token,
                "I_value": rf.i_value,
                "safe_distance": rf.safe_distance,
                "horizon": rf.horizon,
                "uids_seen": traj_summary["uids_seen"],
                "uids_completed": traj_summary["uids_completed"],
                "complete_uid_prefix_N": prefix_n,
                "program_wall_runtime_s": runtime_data.get("Code execution time (seconds)"),
                "generated_agents_x": runtime_data.get("No. of agent along x"),
                "generated_agents_y": runtime_data.get("No. of agent along y"),
                **source_cfg,
            }
            inventory_rows.append(inv)

    if not trajectory_data:
        raise RuntimeError(f"No trajectory JSON is available for traffic {label}; delay/FCFS population cannot be defined")

    # Common population is based only on runs for which trajectory data exists.
    # Missing trajectories are never guessed or imputed.
    prefix_by_run = {k: longest_complete_uid_prefix(v) for k, v in trajectory_data.items()}
    common_n = min(prefix_by_run.values()) if prefix_by_run else 0
    if common_n <= 0:
        raise RuntimeError(f"No common complete UID prefix for traffic {label}")
    common_uids = list(range(1, common_n + 1))

    completed_sets = [
        {uid for uid, r in rows.items() if r.get("complete")}
        for rows in trajectory_data.values()
    ]
    intersection = set.intersection(*completed_sets) if completed_sets else set()
    prefix_set = set(common_uids)
    intersection_extra_count = len(intersection - prefix_set)
    prefix_missing_from_intersection = len(prefix_set - intersection)

    available_count = len(trajectory_data)
    expected_count = len(RADII) * 2
    print(f"\n  Common complete UID prefix over AVAILABLE trajectories: 1..{common_n} ({common_n} agents)")
    print(f"  Trajectory coverage: {available_count}/{expected_count} runs")
    if missing_trajectory_runs:
        print("  Missing trajectory runs (delay will be blank): " + ", ".join(missing_trajectory_runs))
    if intersection_extra_count:
        print(
            f"  NOTE: set intersection contains {intersection_extra_count} additional non-prefix UIDs; "
            "they are intentionally excluded to preserve one contiguous traffic sequence."
        )

    write_csv(case_out / "common_uids.csv", [{"uid": uid} for uid in common_uids])

    # Reference arrival sequence: prefer R=40, fair=False; otherwise use the
    # first available no-fair trajectory, then any available trajectory.
    ref_key = (40, False) if (40, False) in trajectory_data else None
    if ref_key is None:
        nofair_keys = sorted([k for k in trajectory_data if k[1] is False])
        ref_key = nofair_keys[0] if nofair_keys else sorted(trajectory_data)[0]
    ref_rows = trajectory_data[ref_key]

    arrivals = []
    source_time_max_diff = 0.0
    source_axis_mismatch_count = 0
    source_time_mismatch_count = 0
    for uid in common_uids:
        ref = ref_rows[uid]
        t_ref = float(ref["first_seen_time_s"])
        axis_ref = str(ref["axis"])
        for (radius, fair), rows in trajectory_data.items():
            rr = rows.get(uid)
            if rr is None or rr.get("first_seen_time_s") is None:
                source_time_mismatch_count += 1
                continue
            if str(rr["axis"]) != axis_ref:
                source_axis_mismatch_count += 1
            diff = abs(float(rr["first_seen_time_s"]) - t_ref)
            source_time_max_diff = max(source_time_max_diff, diff)
            if diff > DT + 1.0e-7:
                source_time_mismatch_count += 1
        arrivals.append({"uid": uid, "axis": axis_ref, "release_time_s": t_ref})

    fcfs_rows, fcfs_summary = run_event_fcfs(
        arrivals,
        lambda_x=float(case["lambda_x"]),
        lambda_y=float(case["lambda_y"]),
    )
    fcfs_summary.update({
        "traffic_label": label,
        "common_agent_count": common_n,
        "common_population_trajectory_run_count": available_count,
        "missing_trajectory_run_count": len(missing_trajectory_runs),
        "missing_trajectory_runs": ";".join(missing_trajectory_runs),
        "reference_run_for_arrivals": f"R={ref_key[0]}, fair={ref_key[1]}",
        "source_time_consistency_max_abs_s": source_time_max_diff,
        "source_time_mismatch_count": source_time_mismatch_count,
        "source_axis_mismatch_count": source_axis_mismatch_count,
    })
    write_csv(case_out / "fcfs_per_agent.csv", fcfs_rows)
    write_csv(case_out / "fcfs_summary.csv", [fcfs_summary])

    # MILP delay detail: write only runs with available trajectories.  Solver
    # summaries are still created for all 18 requested run folders.
    milp_agent_detail_path = case_out / "milp_common_agent_delays.csv.gz"
    detail_fields = [
        "traffic_label", "lambda_x", "lambda_y", "radius_m", "fair",
        "common_agent_count", "uid", "axis", "source_first_seen_time_s",
        "entry_time_s", "center_time_s", "exit_time_s", "delay_s",
    ]

    with gzip.open(milp_agent_detail_path, "wt", newline="", encoding="utf-8") as gf:
        detail_writer = csv.DictWriter(gf, fieldnames=detail_fields)
        detail_writer.writeheader()

        for radius in RADII:
            for fair in (False, True):
                rf = all_runs[RunKey(label, radius, fair)]
                data_key = (radius, fair)
                trajectory_available = data_key in trajectory_data

                if trajectory_available:
                    rows = trajectory_data[data_key]
                    delays = [float(rows[uid]["delay_s"]) for uid in common_uids]
                    ds = stats(delays)
                    for uid in common_uids:
                        rr = rows[uid]
                        detail_writer.writerow({
                            "traffic_label": label,
                            "lambda_x": case["lambda_x"],
                            "lambda_y": case["lambda_y"],
                            "radius_m": radius,
                            "fair": fair,
                            "common_agent_count": common_n,
                            "uid": uid,
                            "axis": rr["axis"],
                            "source_first_seen_time_s": rr["first_seen_time_s"],
                            "entry_time_s": rr["entry_time_s"],
                            "center_time_s": rr["center_time_s"],
                            "exit_time_s": rr["exit_time_s"],
                            "delay_s": rr["delay_s"],
                        })
                else:
                    ds = stats([])

                print(f"\n    solver analysis R={radius}, fair={fair}")
                solver_summary = parse_solver_run(rf)
                runtime_data = json_load_maybe(rf.runtime_file)
                program_wall = runtime_data.get("Code execution time (seconds)")
                solver_total = solver_summary.get("solver_runtime_s_total")
                solver_fraction = None
                if isinstance(program_wall, (int, float)) and program_wall > 0 and isinstance(solver_total, (int, float)):
                    solver_fraction = float(solver_total) / float(program_wall)

                traj_sum = trajectory_summaries.get(data_key, {})
                run_row = {
                    "traffic_label": label,
                    "lambda_x": case["lambda_x"],
                    "lambda_y": case["lambda_y"],
                    "lambda_total": float(case["lambda_x"]) + float(case["lambda_y"]),
                    "radius_m": radius,
                    "fair": fair,
                    "trajectory_available": trajectory_available,
                    "delay_available": trajectory_available,
                    "missing_trajectory_reason": None if trajectory_available else "vehicles_positions_id JSON missing",
                    "common_agent_count": common_n,
                    "common_population_trajectory_run_count": available_count,
                    "mean_delay_s": ds["mean"],
                    "median_delay_s": ds["median"],
                    "std_delay_s": ds["std"],
                    "p95_delay_s": ds["p95"],
                    "max_delay_s": ds["max"],
                    "total_delay_s": ds["total"] if trajectory_available else None,
                    "program_wall_runtime_s": program_wall,
                    "generated_agents_x": runtime_data.get("No. of agent along x"),
                    "generated_agents_y": runtime_data.get("No. of agent along y"),
                    "solver_runtime_fraction_of_program": solver_fraction,
                    "trajectory_uids_seen": traj_sum.get("uids_seen"),
                    "trajectory_uids_completed": traj_sum.get("uids_completed"),
                    "complete_uid_prefix_N_this_run": prefix_by_run.get(data_key),
                    "week_dir": str(rf.week_dir),
                    **solver_summary,
                }
                run_rows.append(run_row)

    prefix_values = list(prefix_by_run.values())
    common_summary = {
        "traffic_label": label,
        "lambda_x": case["lambda_x"],
        "lambda_y": case["lambda_y"],
        "lambda_total": float(case["lambda_x"]) + float(case["lambda_y"]),
        "common_complete_uid_prefix_N": common_n,
        "common_population_defined_over_available_trajectories": True,
        "available_trajectory_run_count": available_count,
        "expected_trajectory_run_count": expected_count,
        "missing_trajectory_run_count": len(missing_trajectory_runs),
        "missing_trajectory_runs": ";".join(missing_trajectory_runs),
        "set_intersection_completed_uid_count": len(intersection),
        "intersection_extra_nonprefix_uid_count": intersection_extra_count,
        "prefix_missing_from_intersection_count": prefix_missing_from_intersection,
        "source_time_consistency_max_abs_s": source_time_max_diff,
        "source_time_mismatch_count": source_time_mismatch_count,
        "source_axis_mismatch_count": source_axis_mismatch_count,
        "min_complete_prefix_over_available_runs": min(prefix_values),
        "max_complete_prefix_over_available_runs": max(prefix_values),
        "comparison_note": (
            "Runs without trajectory JSON are excluded only from delay/common-population computation. "
            "Their Gurobi problem-size/runtime metrics are retained. No delay is imputed."
        ),
    }

    write_csv(case_out / "run_summary.csv", run_rows)
    write_csv(case_out / "experiment_inventory.csv", inventory_rows)
    write_csv(case_out / "common_population_summary.csv", [common_summary])

    return run_rows, fcfs_summary, common_summary, inventory_rows


# =============================================================================
# Final cross-traffic outputs
# =============================================================================


def build_wide_comparison(milp_rows: Sequence[dict], fcfs_by_traffic: Dict[str, dict]) -> List[dict]:
    grouped: Dict[Tuple[str, int], Dict[bool, dict]] = {}
    for row in milp_rows:
        grouped.setdefault((row["traffic_label"], int(row["radius_m"])), {})[bool(row["fair"])] = row

    out = []
    for (label, radius), pair in sorted(grouped.items(), key=lambda kv: (kv[0][0], kv[0][1])):
        nf = pair.get(False, {})
        fr = pair.get(True, {})
        fcfs = fcfs_by_traffic[label]
        out.append({
            "traffic_label": label,
            "lambda_x": nf.get("lambda_x", fr.get("lambda_x")),
            "lambda_y": nf.get("lambda_y", fr.get("lambda_y")),
            "lambda_total": nf.get("lambda_total", fr.get("lambda_total")),
            "radius_m": radius,
            "common_agent_count": nf.get("common_agent_count", fr.get("common_agent_count")),
            "milp_nofair_mean_delay_s": nf.get("mean_delay_s"),
            "milp_fair_mean_delay_s": fr.get("mean_delay_s"),
            "milp_nofair_p95_delay_s": nf.get("p95_delay_s"),
            "milp_fair_p95_delay_s": fr.get("p95_delay_s"),
            "milp_nofair_max_delay_s": nf.get("max_delay_s"),
            "milp_fair_max_delay_s": fr.get("max_delay_s"),
            "fcfs_mean_virtual_wait_s": fcfs.get("mean_delay_s"),
            "fcfs_p95_virtual_wait_s": fcfs.get("p95_delay_s"),
            "fcfs_theoretical_mg1_mean_wait_s": fcfs.get("theoretical_mg1_mean_wait_s"),
            "nofair_mean_solver_runtime_s": nf.get("solver_runtime_s_mean"),
            "fair_mean_solver_runtime_s": fr.get("solver_runtime_s_mean"),
            "nofair_p95_solver_runtime_s": nf.get("solver_runtime_s_p95"),
            "fair_p95_solver_runtime_s": fr.get("solver_runtime_s_p95"),
            "nofair_max_solver_runtime_s": nf.get("solver_runtime_s_max"),
            "fair_max_solver_runtime_s": fr.get("solver_runtime_s_max"),
            "nofair_total_solver_runtime_s": nf.get("solver_runtime_s_total"),
            "fair_total_solver_runtime_s": fr.get("solver_runtime_s_total"),
            "nofair_mean_model_rows": nf.get("model_rows_mean"),
            "fair_mean_model_rows": fr.get("model_rows_mean"),
            "nofair_mean_model_columns": nf.get("model_columns_mean"),
            "fair_mean_model_columns": fr.get("model_columns_mean"),
            "nofair_mean_original_binary_vars": nf.get("original_binary_vars_mean"),
            "fair_mean_original_binary_vars": fr.get("original_binary_vars_mean"),
            "nofair_mean_presolved_binary_vars": nf.get("presolved_binary_vars_mean"),
            "fair_mean_presolved_binary_vars": fr.get("presolved_binary_vars_mean"),
        })
    return out


def main() -> None:
    start = time.perf_counter()
    OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)

    parameter_rows = [
        {"parameter": "seed", "value": SEED, "note": "single seed study"},
        {"parameter": "radii_m", "value": ",".join(map(str, RADII)), "note": "nine radii"},
        {"parameter": "I_value", "value": I_VALUE, "note": "all selected folders use I_4"},
        {"parameter": "safe_distance_m", "value": D_SAFE, "note": "same-lane d_safe"},
        {"parameter": "cross_flow_separation_m", "value": D_SEP, "note": "I_4 / cross-flow center buffer"},
        {"parameter": "dt_s", "value": DT, "note": "simulation time step"},
        {"parameter": "horizon_N", "value": HORIZON, "note": "MILP prediction horizon"},
        {"parameter": "source_nominal_speed_mps", "value": V_NOMINAL, "note": "traffic generation speed"},
        {"parameter": "u_min_mps2", "value": U_MIN, "note": "control lower bound"},
        {"parameter": "u_max_mps2", "value": U_MAX, "note": "control upper bound"},
        {"parameter": "total_iterations", "value": TOTAL_ITERATIONS, "note": "finite experiment horizon"},
        {"parameter": "stop_add", "value": STOP_ADD, "note": "0: arrivals generated through the whole horizon"},
        {"parameter": "source_x_m", "value": SOURCE_X, "note": "X source"},
        {"parameter": "source_y_m", "value": SOURCE_Y, "note": "Y source"},
        {"parameter": "base_variables_per_active_agent", "value": 12 * HORIZON, "note": "s:4N + u:2N + w:4N + v:2N before pair/fairness auxiliaries"},
        {"parameter": "problem_size_source_of_truth", "value": "Gurobi logs", "note": "report original + presolved rows/columns/variable types"},
        {"parameter": "FCFS_baseline", "value": "one radius-independent event/virtual-wait FCFS per traffic", "note": "strict ascending global UID"},
        {"parameter": "missing_trajectory_policy", "value": "allow", "note": "retain solver/runtime metrics; leave MILP delay blank; common UID prefix uses available trajectories only"},
    ]
    for c in TRAFFIC_CASES:
        parameter_rows.append({
            "parameter": f"{c['label']}_roots",
            "value": f"False={c['false_root']} | True={c['true_root']}",
            "note": f"lambda_x=lambda_y={c['lambda_x']}",
        })
    write_csv(OUTPUT_ROOT / "parameters.csv", parameter_rows)

    runs = discover_all_runs()
    inventory_all: List[dict] = []
    milp_all: List[dict] = []
    fcfs_all: List[dict] = []
    common_all: List[dict] = []
    fcfs_by_traffic: Dict[str, dict] = {}

    for case in TRAFFIC_CASES:
        run_rows, fcfs_summary, common_summary, inventory_rows = analyze_traffic_case(case, runs)
        milp_all.extend(run_rows)
        fcfs_all.append(fcfs_summary)
        common_all.append(common_summary)
        inventory_all.extend(inventory_rows)
        fcfs_by_traffic[case["label"]] = fcfs_summary

        # Check source-code lambda/fairness against the explicit six-root mapping.
        for inv in inventory_rows:
            lx = inv.get("code_lambda_x")
            ly = inv.get("code_lambda_y")
            cf = inv.get("code_fair")
            if isinstance(lx, (int, float)) and abs(float(lx) - float(inv["lambda_x_expected"])) > 1e-12:
                print("WARNING lambda_x mismatch:", inv["source_code_file"], lx, inv["lambda_x_expected"])
            if isinstance(ly, (int, float)) and abs(float(ly) - float(inv["lambda_y_expected"])) > 1e-12:
                print("WARNING lambda_y mismatch:", inv["source_code_file"], ly, inv["lambda_y_expected"])
            if isinstance(cf, bool) and cf != bool(inv["fair"]):
                print("WARNING fair flag mismatch:", inv["source_code_file"], cf, inv["fair"])

    write_csv(OUTPUT_ROOT / "paper_summary.csv", milp_all)
    write_csv(OUTPUT_ROOT / "fcfs_summary.csv", fcfs_all)
    write_csv(OUTPUT_ROOT / "common_population_summary.csv", common_all)
    write_csv(OUTPUT_ROOT / "experiment_inventory.csv", inventory_all)

    wide = build_wide_comparison(milp_all, fcfs_by_traffic)
    write_csv(OUTPUT_ROOT / "paper_comparison_wide.csv", wide)

    master = {
        "created_by": Path(__file__).name,
        "output_root": str(OUTPUT_ROOT),
        "radii": RADII,
        "I_value": I_VALUE,
        "seed": SEED,
        "traffic_cases": TRAFFIC_CASES,
        "milp_run_count": len(milp_all),
        "fcfs_run_count": len(fcfs_all),
        "common_population": common_all,
        "fcfs_summary": fcfs_all,
        "analysis_wall_s": time.perf_counter() - start,
    }
    (OUTPUT_ROOT / "master_summary.json").write_text(
        json.dumps(master, indent=2, allow_nan=False, default=str), encoding="utf-8"
    )

    print("\n" + "=" * 80)
    print("POST-PROCESSING COMPLETE")
    print("=" * 80)
    print(f"Output root: {OUTPUT_ROOT}")
    print(f"MILP summary rows: {len(milp_all)} (expected 54 run folders; missing trajectory rows remain with blank delay)")
    print(f"FCFS summary rows: {len(fcfs_all)} (expected 3)")
    for row in common_all:
        print(
            f"  {row['traffic_label']}: common UID prefix N={row['common_complete_uid_prefix_N']}"
        )
    print("Main files:")
    print("  paper_summary.csv")
    print("  paper_comparison_wide.csv")
    print("  fcfs_summary.csv")
    print("  common_population_summary.csv")
    print("  experiment_inventory.csv")
    print("  master_summary.json")


if __name__ == "__main__":
    main()
